id: AC0B975D3
title: 'Granting the Wish for Immortality: A Prayer for the Long Life of Dzarong Trulshik
  Rinpoche, the Representative of Guru Rinpoche'
type: translation
pechas:
- I745EE12B
- IB437AF24
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:52:59.621505
  last_modified_at: 2023-01-04 11:52:59.621516
  collections:
  - Fourteenth Dalai Lama Series
  - Works of Tibetan Masters
alignment_to_base:
  I745EE12B/0255: '9496'
  IB437AF24/4B52: '9496'
